name: Docker Build Images

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -   name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
      -   name: Login to docker ghcr.io registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: USERNAME
            password: ${{ secrets.CI_TOKEN }}
      -   name: Docker inotify-consumers meta
          id: inotify-consumers
          uses: docker/metadata-action@v3
          with:
            images: |
              ghcr.io/${{ github.repository }}
      -   name: Bake inotify-consumers and push
          uses: docker/bake-action@v2
          with:
            files: |
              ./docker-bake.hcl
              ${{ steps.inotify-consumers.outputs.bake-file }}
            targets: default
            push: true
